#!/bin/sh
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
#
# Filename: target/idunn/initramfs/etc_rc.d_rc.switchroot.sh
# Copyright (C) 2008 - 2009 The OpenSDE Project
#
# More information can be found in the files COPYING and README.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

. /etc/rc.d/functions.in
. /etc/conf/idunn

case "$1" in
stop)
	title "Stoping network interfaces"
	check unet down
	status
	
	title "Moving special filesystems"
	for x in dev sys proc; do
		check mount -o move "/$x" "$rootfs/$x"
	done
	status

	;;
revive)
	title "Moving special filesystems back"
	for x in dev sys proc; do
		check mount -o move "$rootfs/$x" "/$x"
	done
	status

	title "Restarting network interfaces"
	check unet up
	status

	title "Restarting Supervisor"
	check start-stop-daemon -S -b -x /usr/bin/runsvdir -- /var/service/
	status
	;;
esac
