#!/bin/sh
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
#
# Filename: target/idunn/initramfs/init.sh
# Copyright (C) 2008 The OpenSDE Project
#
# More information can be found in the files COPYING and README.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

export PATH

# catch some signals
#
signal_handler() {
	echo "=== trap $* ===" >> /var/log/init-signals.log
}

for x in USR1 USR2 TERM INT; do
	trap "signal_handler $x" $x
done

# start the world
/etc/rc.d/rc.sysinit 2>&1 | tee -a /var/log/init.log

# attach a console
ln -s /etc/console /var/service/

while true; do
	sleep 1;
done
